### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by DuelyDescribedDisarray** [YunoHost-Apps/crabfit_ynh#4]
### Describe the bug

Installation through webadmin fails

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.10.3
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch:1.0~ynh2
- If upgrading, current package version:

### Steps to reproduce
Install Crabfit through the web GUI.

### Expected behavior

Crabfit should be installed.

### Logs

https://paste.yunohost.org/raw/zinulonusa

**Comment by Dazeilad** [comment]
Installation fails here too : https://paste.yunohost.org/raw/ibeleyehex

**Comment by Lezney** [comment]
Thirding this issue:

https://forum.yunohost.org/t/crabfit-failed-to-compile/29412
