### ISSUE TITLE
Wrong poll URL

### ISSUE THREAD

**Issue by dotInTheWind** [YunoHost-Apps/crabfit_ynh#6]
Hi,

When a poll is created, the original "crab.fit" URL is used, instead of the domain URL.
![image](https://github.com/YunoHost-Apps/crabfit_ynh/assets/106312228/510dc1fc-d704-4d67-ac62-34a4b049cca7)

Installed version: 1.0~ynh3

Thanks!

**Comment by limaanto** [comment]
Hey there, thanks for the report!
This is a known issue in [the upstream](https://github.com/GRA0007/crab.fit/issues/297) but I don't have enough JS knowledge to fix it in this package :/
If someone can come up with a fixing patch, I'll be glad to include it.

**Comment by limaanto** [comment]
That is fixed with that patched issued in #7. In addition I opened a PR upstream: https://github.com/GRA0007/crab.fit/pull/330
